version: '3.8'

services:
  backend:
    build: ./
    ports:
      - "5600:5500"
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app
      - /app/node_modules

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
      - "8001:8001"  # Redis Insight UI
    restart: always
